services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PWD}
      - plugins.security.disabled=false
    ports:
      - "9200:9200"
    networks:
      - opensearch-net

networks:
  opensearch-net: